blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation

login:

    path: /connexion

    defaults:

        _controller: MainBundle:AdminViewController

login_check:

    path: /login_check


logout:

    path: /logout