# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AdminBundle\Entity\User : plaintext
    

  providers:
        user_db:
            entity: { class: AdminBundle\Entity\User, property: username}       
        
  firewalls:
      
    main:
      pattern:      ^/
      anonymous:    true
      
     
      form_login:
        default_target_path: /accueil
        login_path: /connexion
        check_path: /login_check
      logout:
        path:       /logout
        target:     /

  access_control:

      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: ROLE_ADMIN }
      