<?php

namespace AdminBundle\Repository;

/**
 * EtatpublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatpublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
